### ISSUE TITLE
l3regex.sty not found

### ISSUE THREAD

**Issue by Aariq** [ropenscilabs/vitae#45]
When I try to knit a moderncv template, it calls tidytex to search for l3regex.sty, but that isn't found and I get the following error in the R Markdown tab:
---

```
tlmgr search --file --global '/l3regex.sty'
! LaTeX Error: File `l3regex.sty' not found.

! Emergency stop.
<read *> 

Error: Failed to compile Untitled.tex. See Untitled.log for more info.
In addition: Warning message:
In parse_packages(logfile, quiet = c(TRUE, FALSE, FALSE)) :
  Failed to find a package that contains l3regex.sty
Execution halted
```

**Comment by robjhyndman** [comment]
That seems to be a change in the latest version of texlive used by tinytex. I've updated the files. Try now.

You will need to replace the moderncv.cls file with this one: https://raw.githubusercontent.com/ropenscilabs/vitae/master/inst/rmarkdown/templates/moderncv/skeleton/moderncv.cls

**Comment by Aariq** [comment]
This worked, but now "FontAwesome" can't be found.  Is this an issue I should submit to tinytex?

**Comment by APaganini** [comment]
@robjhyndman In [moderncv.cls file](https://raw.githubusercontent.com/ropenscilabs/vitae/master/inst/rmarkdown/templates/moderncv/skeleton/moderncv.cls) , I noticed that, beside replacing `\RequirePackage{l3regex}` with `\RequirePackage{expl3}`, the following lines have been removed:

```
% loads a color scheme
% usage: \moderncvcolor{<color scheme name>}
\newcommand*{\moderncvcolor}[1]{%
\RequirePackage{moderncvcolor#1}}
```
I don't know if this is intentional, but this can lead to the following error (when using pdflatex)

```
! Undefined control sequence.
\\moderncvtheme [#1]#2->\moderncvcolor 
                                       {#1}\moderncvstyle {#2}
l.3 \moderncvtheme[blue]{classic}
```
I write it here in case someone else hits the same issue (which is fixed by readding the 3 lines above.

**Comment by kelly-sovacool** [comment]
Thanks @APaganini! For those who don't want to manually edit the file, here's a version of the newer [`moderncv.cls`](https://raw.githubusercontent.com/kelly-sovacool/latex-cv/master/moderncv/moderncv.cls) with those lines added back in.

**Comment by mitchelloharawild** [comment]
Thanks, I've updated the package to include this addition.
